library(ggplot2)
library(dplyr)
library(rnaturalearth)
library(rnaturalearthdata)
library(readr)
library(RColorBrewer)
library(sf)
library(cowplot)
df <- read_csv("dados_paises_sus_estrangeiros.csv")
df <- df %>%
  group_by(pais) %>%
  summarise(qtd = n())
total_geral <- 64497987
df <- df %>%
  mutate(percentual = (qtd / total_geral) * 100)
df$pais_rnaturalearth <- recode(df$pais,
                                "BOLIVIA"="Bolivia",
                                "BARBADOS"="Barbados",
                                "REPUBLICA ARABE DO EGITO"="Egypt",
                                "BRUNEI"="Brunei",
                                "RODESIA (ZIMBABWE)"="Zimbabwe",
                                "BOTSUANA"="Botswana",
                                "PERU"="Peru",
                                "ABISSINIA"="Ethiopia",
                                "BAHREIN"="Bahrain",
                                "ESPANHA"="Spain",
                                "RUANDA"="Rwanda",
                                "NAMIBIA"="Namibia",
                                "CHILE"="Chile",
                                "VENEZUELA"="Venezuela",
                                "BERMUDAS"="Bermuda",
                                "ITALIA"="Italy",
                                "BECHUANALANDIA"="Botswana",
                                "REPUBLICA DO HAITI"="Haiti",
                                "MARTINICA"="Martinique",
                                "EIRE"="Ireland",
                                "MEXICO"="Mexico",
                                "UZBEQUISTAO"="Uzbekistan",
                                "INDIA"="India",
                                "ALEMANHA"="Germany",
                                "PORTUGAL"="Portugal",
                                "CUBA"="Cuba",
                                "COLOMBIA"="Colombia",
                                "ILHAS SANTA CRUZ"="Solomon Islands",
                                "ARGENTINA"="Argentina",
                                "PAIS DE GALES"="Wales",
                                "ESTADOS UNIDOS DA AMERICA (EUA)"="United States of America",
                                "JAPAO"="Japan",
                                "SENEGAL"="Senegal",
                                "PARAGUAI"="Paraguay",
                                "GANA"="Ghana",
                                "ESCOCIA"="Scotland",
                                "ARABIA SAUDITA"="Saudi Arabia",
                                "UCRANIA"="Ukraine",
                                "GRECIA"="Greece",
                                "ANGOLA"="Angola",
                                "EQUADOR"="Ecuador",
                                "BENIN"="Benin",
                                "MOCAMBIQUE"="Mozambique",
                                "TUNISIA"="Tunisia",
                                "CONGO"="Congo",
                                "REPUBLICA DE MALTA"="Malta",
                                "CHINA"="China",
                                "GIBRALTAR"="Gibraltar",
                                "INGLATERRA"="England",
                                "ILHAS FAROES"="Faroe Islands",
                                "URUGUAI"="Uruguay",
                                "GRA-BRETANHA"="United Kingdom",
                                "ILHAS VIRGENS AMERICANAS"="United States Virgin Islands",
                                "RESERVADO"=NA_character_,
                                "ILHAS DO CANAL"="Channel Islands",
                                "GUINE BISSAU"="Guinea-Bissau",
                                "COMUNIDADE DAS BAHAMAS"="Bahamas",
                                "ANTARTICO BRITANICO, TERRITORIO"="British Antarctic Territory",
                                "SUECIA"="Sweden",
                                "ILHAS VIRGENS BRITANICAS"="British Virgin Islands",
                                "RUSSIA"="Russia",
                                "BURKINA FASSO"="Burkina Faso",
                                "REPUBLICA DA BIELORRUSSIA"="Belarus",
                                "ILHAS TURCA"="Turks and Caicos Islands",
                                "GUATEMALA"="Guatemala",
                                "COSTA RICA"="Costa Rica",
                                "CANADA"="Canada",
                                "LETONIA"="Latvia",
                                "MONTE SERRAT"="Montserrat",
                                "AUSTRALIA"="Australia",
                                "HOLANDA"="Netherlands",
                                "CHIPRE"="Cyprus",
                                "FRANCA"="France",
                                "TERRAS AUSTRAIS"="Australian Antarctic Territory",
                                "SVALBARD E JAN MAYER,IS"="Svalbard",
                                "ISLANDIA"="Iceland",
                                "SAO TOME E PRINCIPE"="Sao Tome and Principe",
                                "IUGOSLAVIA"="Serbia",
                                "ALBANIA"="Albania",
                                "ARGELIA"="Algeria",
                                "POLONIA"="Poland",
                                "LIBERIA"="Liberia",
                                "HUNGRIA"="Hungary",
                                "COREIA"="South Korea",
                                "GUIANA FRANCESA"="French Guiana",
                                "CAMAROES"="Cameroon",
                                "ILHAS TOKELAU"="Tokelau",
                                "ANDORRA"="Andorra",
                                "PALESTINA"="Palestine",
                                "BULGARIA"="Bulgaria",
                                "BIRMANIA"="Myanmar",
                                "REPUBLICA DOMINICANA"="Dominican Republic",
                                "ILHAS MACDONAL E HEARD"="Heard Island and McDonald Islands",
                                "FINLANDIA"="Finland",
                                "SANTA LUCIA"="Saint Lucia",
                                "QUENIA"="Kenya",
                                "MADAGASCAR"="Madagascar",
                                "BANGLADESH"="Bangladesh",
                                "AFAR FRANCES"="French Afar",
                                "NIGERIA"="Nigeria",
                                "NICARAGUA"="Nicaragua",
                                "PANAMA(ZONA DO CANAL)"="Panama",
                                "OMAN"="Oman",
                                "BOSNIA HERZEGOVINA"="Bosnia and Herzegovina",
                                "HONDURAS BRITANICAS"="British Honduras",
                                "PORTO RICO"="Puerto Rico",
                                "CHINA (TAIWAN)"="Taiwan",
                                "SUICA"="Switzerland",
                                "GAMBIA"="Gambia",
                                "QUITASUENO"="Quisqueya",
                                "MALAWI"="Malawi",
                                "BELGICA"="Belgium",
                                "CABO VERDE"="Cape Verde",
                                "JAMAICA"="Jamaica",
                                "TERR. ANTARTICO DA AUSTRALIA"="Australian Antarctic Territory",
                                "AUSTRIA"="Austria",
                                "ETIOPIA"="Ethiopia",
                                "SAO CRISTOVAO"="Saint Kitts and Nevis",
                                "BASHKISTA"="Bashkortostan",
                                "IEMEN"="Yemen",
                                "QUIRGUISTAO"="Kyrgyzstan",
                                "LESOTO"="Lesotho",
                                "CEILAO"="Sri Lanka",
                                "INDONESIA"="Indonesia",
                                "GORNO ALTAI"="Gorno-Altai",
                                "MAURICIO"="Mauritius",
                                "SAARA ESPANHOL"="Spanish Sahara",
                                "ANTIGA E. DEP. BARBUDA"="Antigua and Barbuda",
                                "IRLANDA DO NORTE"="Northern Ireland",
                                "MAURITANIA"="Mauritania",
                                "TERRIT. BRITANICO DO OCEANO INDICO"="British Indian Ocean Territory",
                                "CURACAO"="Curacao",
                                "IRLANDA"="Ireland",
                                "TURQUIA"="Turkey",
                                "ILHAS LINHA"="Line Islands",
                                "MADEIRA"="Madeira",
                                "SURINAME"="Suriname",
                                "PAISES BAIXOS"="Netherlands",
                                "CEUTA E MELILLA"="Ceuta and Melilla",
                                "JORDANIA"="Jordan",
                                "ESTADO DA CIDADE DO VATICANO"="Vatican",
                                "TADJIQUISTAO"="Tajikistan",
                                "ILHAS NOVAS HEBRIDAS"="New Hebrides",
                                "ILHAS KINGMAN REEF"="Kingman Reef",
                                "GUAM"="Guam",
                                "MARROCOS"="Morocco",
                                "ARUBA"="Aruba",
                                "MIANMA"="Myanmar",
                                "ANTILHAS HOLANDESAS"="Netherlands Antilles",
                                "ILHAS WAKE"="Wake Island",
                                "REPUBLICA DA AFRICA DO SUL"="South Africa",
                                "LIECHTENSTEIN"="Liechtenstein",
                                "ISRAEL"="Israel",
                                "ANTARTICO ARGENTINO"="Argentine Antarctica",
                                "SARAWAK"="Sarawak",
                                "DINAMARCA"="Denmark",
                                "REPUBLICA GUIANA"="Guyana",
                                "GUINE"="Guinea",
                                "CATAR"="Qatar",
                                "GEORGIA"="Georgia",
                                "SOMALIA, REPUBLICA"="Somalia",
                                "ILHAS GUADALUPE"="Guadeloupe",
                                "COSTA DO MARFIM"="Ivory Coast",
                                "REPUBLICA DE EL SALVADOR"="El Salvador",
                                "ILHAS COOK"="Cook Islands",
                                "KABARDINO BALKAR"="Kabardino-Balkaria",
                                "ROMENIA"="Romania",
                                "NORUEGA"="Norway",
                                "TAILANDIA"="Thailand",
                                "REPUBLICA CENTRO AFRICANA"="Central African Republic",
                                "LITUANIA"="Lithuania",
                                "ILHAS BALEARES"="Balearic Islands",
                                "LUXEMBURGO"="Luxembourg",
                                "FILIPINAS"="Philippines",
                                "ST. PIERRE ET MIQUELON"="Saint Pierre and Miquelon",
                                "IRAQUE"="Iraq",
                                "ACORES"="Azores",
                                "NOVA GUINE"="New Guinea",
                                "BURYAT"="Buryatia",
                                "ILHAS PALAU"="Palau",
                                "CROACIA"="Croatia",
                                "LIBIA"="Libya",
                                "TIMOR"="Timor-Leste",
                                "ARMENIA"="Armenia",
                                "SIRIA"="Syria",
                                "REPUBLICA DO GABAO"="Gabon",
                                "TOGO"="Togo",
                                "PAQUISTAO"="Pakistan",
                                "MALI"="Mali",
                                "LIBANO"="Lebanon",
                                "ALTA VOLTA"="Burkina Faso",
                                "ASHMORE E CARTIER"="Ashmore and Cartier Islands",
                                "EMIRADOS ARABES UNIDOS"="United Arab Emirates",
                                "KUWAIT"="Kuwait",
                                "SAO VICENTE"="Saint Vincent and the Grenadines",
                                "ARQUIPELAGO MANAHIKI"="Manahiki",
                                "MONGOLIA"="Mongolia",
                                "ZAIRE"="Congo - Kinshasa",
                                "ESLOVENIA"="Slovenia",
                                "AFEGANISTAO"="Afghanistan",
                                "VIETNA DO NORTE"="North Vietnam",
                                "UGANDA"="Uganda",
                                "IRA"="Iran",
                                "ASCENSAO E TRISTAO DA CUNHA,IS"="Ascension and Tristan da Cunha",
                                "ESLOVAQUIA"="Slovakia",
                                "HONDURAS"="Honduras",
                                "CAZAQUISTAO"="Kazakhstan",
                                "ZIMBABWE"="Zimbabwe",
                                "ZAMBIA"="Zambia",
                                "SUDAO"="Sudan",
                                "PRACAS NORTE AFRICANAS"="Northern African Territories",
                                "SERRA LEOA"="Sierra Leone",
                                "ILHAS SERRANAS"="Serran Islands",
                                "DAGESTA"="Dagestan",
                                "MALDIVAS,IS"="Maldives",
                                "TUVALU"="Tuvalu",
                                "NOVA ZELANDIA"="New Zealand",
                                "NGUANE"="Eswatini",
                                "PROTETOR DO SUDOESTE AFRICANO"="South-West African Protectorate",
                                "TRINIDAD E TOBAGO"="Trinidad and Tobago",
                                "ILHA JOHNSTON E SAND"="Johnston Island",
                                "IFNI"="Ifni",
                                "DJIBUTI"="Djibouti",
                                "REPUBLICA DA MACEDONIA"="North Macedonia",
                                "TONGA"="Tonga",
                                "ANTARTICO NORUEGUES"="Norwegian Antarctica",
                                "POLINESIA FRANCESA"="French Polynesia",
                                "BHUTAN"="Bhutan",
                                "IEMEN DO SUL"="South Yemen",
                                "BURUNDI"="Burundi",
                                "ANTARTICA FRANCESA"="French Antarctic Territory",
                                "ILHAS FALKLANDS"="Falkland Islands",
                                "VIETNA DO SUL"="South Vietnam",
                                "KALIMATAN"="Kalimantan",
                                "ESTADOS ASSOC. DAS ANTILHAS"="Netherlands Antilles",
                                "KARA KALPAK"="Kara-Kalpak",
                                "MACAU"="Macau",
                                "SAMOA OCIDENTAL"="Western Samoa",
                                "PANAMA"="Panama",
                                "BELIZE"="Belize",
                                "TUVIN"="Tuva",
                                "GROENLANDIA"="Greenland",
                                "ILHAS CHRISTMAS"="Christmas Island",
                                "ILHAS WALLIS E FUTUNA"="Wallis and Futuna Islands",
                                "ILHAS BAKER"="Baker Island",
                                "TARTARIA"="Tartary",
                                "HONG-KONG"="Hong Kong",
                                "SABAH"="Sabah",
                                "ILHAS PITCAIRIN"="Pitcairn Islands",
                                "CHADE"="Chad",
                                "TERRITORIO DE COCOS"="Cocos Islands",
                                "SAN MARINO"="San Marino",
                                "SAMOA AMERICANA"="American Samoa",
                                "TRANSKEI"="Transkei",
                                "REPUBLICA DO NIGER"="Niger",
                                "UNIAO SOVIETICA"="Soviet Union",
                                "REPUBLICA TCHECA"="Czech Republic",
                                "CARELIA"="Karelia",
                                "ILHAS MALVINAS"="Falkland Islands",
                                "ILHAS GILBERT"="Gilbert Islands",
                                "ILHAS COSMOLEDO (LOMORES)"="Cosmoledo Islands",
                                "COMUNIDADE DOMINICANA"="Dominican Community",
                                "KOMI"="Komi",
                                "ILHAS MARSHALL"="Marshall Islands",
                                "MOLDAVIA"="Moldova",
                                "NEPAL"="Nepal",
                                "TANZANIA"="Tanzania",
                                "PAPUA NOVA GUINE"="Papua New Guinea",
                                "KALMIR"="Kalmir",
                                "RUIQUIU,IS"="Ruiqui Island",
                                "GAZA"="Gaza",
                                "ANTARTICO CHILENO"="Chilean Antarctica",
                                "ILHAS MARIANAS"="Mariana Islands",
                                "TREGUA, ESTADO"="Truce State",
                                "KARACHAEVOCHERKESS"="Karachay-Cherkess",
                                "ARQUIPELAGO DE BISMARK"="Bismarck Archipelago",
                                "GRANDA"="Grenada",
                                "ILHAS NIUE"="Niue",
                                "DAOME"="Dahomey",
                                "MONACO"="Monaco",
                                "TANGANICA"="Tanganyika",
                                "ILHAS COMORES"="Comoros",
                                "RONCADOR"="Roncador",
                                "ILHAS DO PACIFICO"="Pacific Islands",
                                "ILHA MILHOS"="Milhos Island",
                                "MALASIA"="Malaysia",
                                "CINGAPURA"="Singapore",
                                "ESTONIA"="Estonia",
                                "MONTENEGRO"="Montenegro",
                                "CHUVASH"="Chuvashia",
                                "MARI"="Mari",
                                "SERVIA"="Serbia",
                                "ILHAS PASCOA"="Easter Island",
                                "LAOS"="Laos",
                                "ILHAS HOWLAND E JARVIS"="Howland and Jarvis Islands",
                                "ILHAS TURKS E CAICOS"="Turks and Caicos Islands",
                                "ILHAS NOVA CALEDONIA"="New Caledonia",
                                "AZERBAIJAO"="Azerbaijan",
                                "KMER/CAMBOJA"="Cambodia",
                                "SEYCHELLES"="Seychelles",
                                "MASCATE"="Muscat",
                                "GUINE EQUATORIAL"="Equatorial Guinea",
                                "SANTA HELENA"="Saint Helena",
                                "SRI-LANKA"="Sri Lanka",
                                "ILHAS CANTAO E ENDERBURG"="Canton and Enderbury Islands",
                                "YAKUT"="Yakut",
                                "ILHAS CANARIAS"="Canary Islands",
                                "TCHECOSLOVAQUIA"="Czechoslovakia",
                                "ARQUIPELAGO MIDWAY"="Midway Islands",
                                "SUAZILANDIA"="Eswatini"
)
world <- ne_countries(scale = "medium", returnclass = "sf")
world_data <- left_join(world, df, by = c("name" = "pais_rnaturalearth"))
criar_mapa_continente <- function(continente_nome, continente_filtro, xlim, ylim) {
  world_continente <- world_data %>%
    filter(continent %in% continente_filtro)
  world_data_centroides <- world_continente %>%
    filter(!is.na(qtd)) %>%
    mutate(centroide = st_point_on_surface(geometry)) %>%
    mutate(
      X = st_coordinates(centroide)[, 1],
      Y = st_coordinates(centroide)[, 2]
    )
  p <- ggplot() +
    geom_sf(data = world_continente, aes(fill = percentual), 
            color = "gray30", linewidth = 0.3) +
    geom_point(data = world_data_centroides, 
               aes(x = X, y = Y, size = qtd),
               color = "black", 
               alpha = 0.5, 
               shape = 16) +
    scale_fill_gradientn(
      colors = brewer.pal(9, "YlOrRd"),
      na.value = "grey95",
      labels = function(x) paste0(round(x, 2), "%")
    ) +
    scale_size_continuous(
      range = c(2, 20),
      guide = "none"
    ) +
    coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
    theme_minimal() +
    guides(
      fill = guide_colorbar(order = 1, title.position = "top", title.hjust = 0.5),
      size = "none"
    ) +
    theme_minimal() +
    theme(
      legend.position = "bottom",
      legend.box = "vertical",
      legend.text = element_text(size = 9),
      legend.title = element_text(size = 10),
      legend.spacing.x = unit(1, "cm"),
      legend.spacing.y = unit(0.5, "cm"),
      legend.key.width = unit(2, "cm"),
      legend.key.height = unit(0.5, "cm"),
      plot.title = element_text(size = 13, face = "plain", hjust = 0.5),
      plot.caption = element_text(size = 8, hjust = 0, color = "gray40"),
      plot.margin = margin(5,5,5,5),
      panel.background = element_rect(fill = "white", color = NA),
      plot.background = element_rect(fill = "white", color = NA),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank()
    ) +
    labs(
      title = paste0("Nacionalidade dos pacientes com internações de urgência no SUS entre 2019 e agosto de 2025 - ", continente_nome),
      fill = paste0("Percentual do total\n(", format(total_geral, big.mark = ".", scientific = FALSE), ")"),
      caption = "Fonte: SIH/SUS – Sistema de Informações Hospitalares do SUS (DATASUS)"
    )
  return(p)
}
mapa_america_sul <- criar_mapa_continente(
  "América do Sul", 
  c("South America"),
  xlim = c(-85, -30),
  ylim = c(-60, 15)
)
mapa_america_norte <- criar_mapa_continente(
  "América do Norte e Central",
  c("North America"),
  xlim = c(-170, -50),
  ylim = c(5, 75)
)
mapa_europa <- criar_mapa_continente(
  "Europa",
  c("Europe"),
  xlim = c(-25, 45),
  ylim = c(35, 72)
)
mapa_africa <- criar_mapa_continente(
  "África",
  c("Africa"),
  xlim = c(-20, 55),
  ylim = c(-40, 40)
)
mapa_asia <- criar_mapa_continente(
  "Ásia",
  c("Asia"),
  xlim = c(25, 150),
  ylim = c(-15, 60)
)
mapa_oceania <- criar_mapa_continente(
  "Oceania",
  c("Oceania"),
  xlim = c(110, 180),
  ylim = c(-50, 5)
)
plot_grid(mapa_america_sul, mapa_america_norte, mapa_europa, mapa_africa, mapa_asia, mapa_oceania, ncol = 2, rel_widths = c(1,1), rel_heights = c(1,1,1))
ggsave("mapa_america_sul.png", mapa_america_sul, width = 12, height = 8, dpi = 300)
ggsave("mapa_america_norte.png", mapa_america_norte, width = 12, height = 8, dpi = 300)
ggsave("mapa_europa.png", mapa_europa, width = 12, height = 8, dpi = 300)
ggsave("mapa_africa.png", mapa_africa, width = 12, height = 8, dpi = 300)
ggsave("mapa_asia.png", mapa_asia, width = 12, height = 8, dpi = 300)
ggsave("mapa_oceania.png", mapa_oceania, width = 12, height = 8, dpi = 300)