import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
from matplotlib.ticker import FuncFormatter
df = pd.read_csv("dados_paises_sus_estrangeiros.csv")
df_grouped = df.groupby('pais').size().reset_index(name='qtd')
total_geral = 64497987
df_grouped['percentual'] = (df_grouped['qtd'] / total_geral) * 100
recode_dict = {
    "BOLIVIA": "Bolivia",
    "BARBADOS": "Barbados",
    "REPUBLICA ARABE DO EGITO": "Egypt",
    "BRUNEI": "Brunei",
    "RODESIA (ZIMBABWE)": "Zimbabwe",
    "BOTSUANA": "Botswana",
    "PERU": "Peru",
    "ABISSINIA": "Ethiopia",
    "BAHREIN": "Bahrain",
    "ESPANHA": "Spain",
    "RUANDA": "Rwanda",
    "NAMIBIA": "Namibia",
    "CHILE": "Chile",
    "VENEZUELA": "Venezuela",
    "BERMUDAS": "Bermuda",
    "ITALIA": "Italy",
    "BECHUANALANDIA": "Botswana",
    "REPUBLICA DO HAITI": "Haiti",
    "MARTINICA": "Martinique",
    "EIRE": "Ireland",
    "MEXICO": "Mexico",
    "UZBEQUISTAO": "Uzbekistan",
    "INDIA": "India",
    "ALEMANHA": "Germany",
    "PORTUGAL": "Portugal",
    "CUBA": "Cuba",
    "COLOMBIA": "Colombia",
    "ILHAS SANTA CRUZ": "Solomon Islands",
    "ARGENTINA": "Argentina",
    "PAIS DE GALES": "Wales",
    "ESTADOS UNIDOS DA AMERICA (EUA)": "United States of America",
    "JAPAO": "Japan",
    "SENEGAL": "Senegal",
    "PARAGUAI": "Paraguay",
    "GANA": "Ghana",
    "ESCOCIA": "Scotland",
    "ARABIA SAUDITA": "Saudi Arabia",
    "UCRANIA": "Ukraine",
    "GRECIA": "Greece",
    "ANGOLA": "Angola",
    "EQUADOR": "Ecuador",
    "BENIN": "Benin",
    "MOCAMBIQUE": "Mozambique",
    "TUNISIA": "Tunisia",
    "CONGO": "Congo",
    "REPUBLICA DE MALTA": "Malta",
    "CHINA": "China",
    "GIBRALTAR": "Gibraltar",
    "INGLATERRA": "England",
    "ILHAS FAROES": "Faroe Islands",
    "URUGUAI": "Uruguay",
    "GRA-BRETANHA": "United Kingdom",
    "ILHAS VIRGENS AMERICANAS": "United States Virgin Islands",
    "RESERVADO": None,
    "ILHAS DO CANAL": "Channel Islands",
    "GUINE BISSAU": "Guinea-Bissau",
    "COMUNIDADE DAS BAHAMAS": "Bahamas",
    "ANTARTICO BRITANICO, TERRITORIO": "British Antarctic Territory",
    "SUECIA": "Sweden",
    "ILHAS VIRGENS BRITANICAS": "British Virgin Islands",
    "RUSSIA": "Russia",
    "BURKINA FASSO": "Burkina Faso",
    "REPUBLICA DA BIELORRUSSIA": "Belarus",
    "ILHAS TURCA": "Turks and Caicos Islands",
    "GUATEMALA": "Guatemala",
    "COSTA RICA": "Costa Rica",
    "CANADA": "Canada",
    "LETONIA": "Latvia",
    "MONTE SERRAT": "Montserrat",
    "AUSTRALIA": "Australia",
    "HOLANDA": "Netherlands",
    "CHIPRE": "Cyprus",
    "FRANCA": "France",
    "TERRAS AUSTRAIS": "Australian Antarctic Territory",
    "SVALBARD E JAN MAYER,IS": "Svalbard",
    "ISLANDIA": "Iceland",
    "SAO TOME E PRINCIPE": "Sao Tome and Principe",
    "IUGOSLAVIA": "Serbia",
    "ALBANIA": "Albania",
    "ARGELIA": "Algeria",
    "POLONIA": "Poland",
    "LIBERIA": "Liberia",
    "HUNGRIA": "Hungary",
    "COREIA": "South Korea",
    "GUIANA FRANCESA": "French Guiana",
    "CAMAROES": "Cameroon",
    "ILHAS TOKELAU": "Tokelau",
    "ANDORRA": "Andorra",
    "PALESTINA": "Palestine",
    "BULGARIA": "Bulgaria",
    "BIRMANIA": "Myanmar",
    "REPUBLICA DOMINICANA": "Dominican Republic",
    "ILHAS MACDONAL E HEARD": "Heard Island and McDonald Islands",
    "FINLANDIA": "Finland",
    "SANTA LUCIA": "Saint Lucia",
    "QUENIA": "Kenya",
    "MADAGASCAR": "Madagascar",
    "BANGLADESH": "Bangladesh",
    "AFAR FRANCES": "French Afar",
    "NIGERIA": "Nigeria",
    "NICARAGUA": "Nicaragua",
    "PANAMA(ZONA DO CANAL)": "Panama",
    "OMAN": "Oman",
    "BOSNIA HERZEGOVINA": "Bosnia and Herzegovina",
    "HONDURAS BRITANICAS": "British Honduras",
    "PORTO RICO": "Puerto Rico",
    "CHINA (TAIWAN)": "Taiwan",
    "SUICA": "Switzerland",
    "GAMBIA": "Gambia",
    "QUITASUENO": "Quisqueya",
    "MALAWI": "Malawi",
    "BELGICA": "Belgium",
    "CABO VERDE": "Cape Verde",
    "JAMAICA": "Jamaica",
    "TERR. ANTARTICO DA AUSTRALIA": "Australian Antarctic Territory",
    "AUSTRIA": "Austria",
    "ETIOPIA": "Ethiopia",
    "SAO CRISTOVAO": "Saint Kitts and Nevis",
    "BASHKISTA": "Bashkortostan",
    "IEMEN": "Yemen",
    "QUIRGUISTAO": "Kyrgyzstan",
    "LESOTO": "Lesotho",
    "CEILAO": "Sri Lanka",
    "INDONESIA": "Indonesia",
    "GORNO ALTAI": "Gorno-Altai",
    "MAURICIO": "Mauritius",
    "SAARA ESPANHOL": "Spanish Sahara",
    "ANTIGA E. DEP. BARBUDA": "Antigua and Barbuda",
    "IRLANDA DO NORTE": "Northern Ireland",
    "MAURITANIA": "Mauritania",
    "TERRIT. BRITANICO DO OCEANO INDICO": "British Indian Ocean Territory",
    "CURACAO": "Curacao",
    "IRLANDA": "Ireland",
    "TURQUIA": "Turkey",
    "ILHAS LINHA": "Line Islands",
    "MADEIRA": "Madeira",
    "SURINAME": "Suriname",
    "PAISES BAIXOS": "Netherlands",
    "CEUTA E MELILLA": "Ceuta and Melilla",
    "JORDANIA": "Jordan",
    "ESTADO DA CIDADE DO VATICANO": "Vatican",
    "TADJIQUISTAO": "Tajikistan",
    "ILHAS NOVAS HEBRIDAS": "New Hebrides",
    "ILHAS KINGMAN REEF": "Kingman Reef",
    "GUAM": "Guam",
    "MARROCOS": "Morocco",
    "ARUBA": "Aruba",
    "MIANMA": "Myanmar",
    "ANTILHAS HOLANDESAS": "Netherlands Antilles",
    "ILHAS WAKE": "Wake Island",
    "REPUBLICA DA AFRICA DO SUL": "South Africa",
    "LIECHTENSTEIN": "Liechtenstein",
    "ISRAEL": "Israel",
    "ANTARTICO ARGENTINO": "Argentine Antarctica",
    "SARAWAK": "Sarawak",
    "DINAMARCA": "Denmark",
    "REPUBLICA GUIANA": "Guyana",
    "GUINE": "Guinea",
    "CATAR": "Qatar",
    "GEORGIA": "Georgia",
    "SOMALIA, REPUBLICA": "Somalia",
    "ILHAS GUADALUPE": "Guadeloupe",
    "COSTA DO MARFIM": "Ivory Coast",
    "REPUBLICA DO EL SALVADOR": "El Salvador",
    "ILHAS COOK": "Cook Islands",
    "KABARDINO BALKAR": "Kabardino-Balkaria",
    "ROMENIA": "Romania",
    "NORUEGA": "Norway",
    "TAILANDIA": "Thailand",
    "REPUBLICA CENTRO AFRICANA": "Central African Republic",
    "LITUANIA": "Lithuania",
    "ILHAS BALEARES": "Balearic Islands",
    "LUXEMBURGO": "Luxembourg",
    "FILIPINAS": "Philippines",
    "ST. PIERRE ET MIQUELON": "Saint Pierre and Miquelon",
    "IRAQUE": "Iraq",
    "ACORES": "Azores",
    "NOVA GUINE": "New Guinea",
    "BURYAT": "Buryatia",
    "ILHAS PALAU": "Palau",
    "CROACIA": "Croatia",
    "LIBIA": "Libya",
    "TIMOR": "Timor-Leste",
    "ARMENIA": "Armenia",
    "SIRIA": "Syria",
    "REPUBLICA DO GABAO": "Gabon",
    "TOGO": "Togo",
    "PAQUISTAO": "Pakistan",
    "MALI": "Mali",
    "LIBANO": "Lebanon",
    "ALTA VOLTA": "Burkina Faso",
    "ASHMORE E CARTIER": "Ashmore and Cartier Islands",
    "EMIRADOS ARABES UNIDOS": "United Arab Emirates",
    "KUWAIT": "Kuwait",
    "SAO VICENTE": "Saint Vincent and the Grenadines",
    "ARQUIPELAGO MANAHIKI": "Manahiki",
    "MONGOLIA": "Mongolia",
    "ZAIRE": "Congo - Kinshasa",
    "ESLOVENIA": "Slovenia",
    "AFEGANISTAO": "Afghanistan",
    "VIETNA DO NORTE": "North Vietnam",
    "UGANDA": "Uganda",
    "IRA": "Iran",
    "ASCENSAO E TRISTAO DA CUNHA,IS": "Ascension and Tristan da Cunha",
    "ESLOVAQUIA": "Slovakia",
    "HONDURAS": "Honduras",
    "CAZAQUISTAO": "Kazakhstan",
    "ZIMBABWE": "Zimbabwe",
    "ZAMBIA": "Zambia",
    "SUDAO": "Sudan",
    "PRACAS NORTE AFRICANAS": "Northern African Territories",
    "SERRA LEOA": "Sierra Leone",
    "ILHAS SERRANAS": "Serran Islands",
    "DAGESTA": "Dagestan",
    "MALDIVAS,IS": "Maldives",
    "TUVALU": "Tuvalu",
    "NOVA ZELANDIA": "New Zealand",
    "NGUANE": "Eswatini",
    "PROTETOR DO SUDOESTE AFRICANO": "South-West African Protectorate",
    "TRINIDAD E TOBAGO": "Trinidad and Tobago",
    "ILHA JOHNSTON E SAND": "Johnston Island",
    "IFNI": "Ifni",
    "DJIBUTI": "Djibouti",
    "REPUBLICA DA MACEDONIA": "North Macedonia",
    "TONGA": "Tonga",
    "ANTARTICO NORUEGUES": "Norwegian Antarctica",
    "POLINESIA FRANCESA": "French Polynesia",
    "BHUTAN": "Bhutan",
    "IEMEN DO SUL": "South Yemen",
    "BURUNDI": "Burundi",
    "ANTARTICA FRANCESA": "French Antarctic Territory",
    "ILHAS FALKLANDS": "Falkland Islands",
    "VIETNA DO SUL": "South Vietnam",
    "KALIMATAN": "Kalimantan",
    "ESTADOS ASSOC. DAS ANTILHAS": "Netherlands Antilles",
    "KARA KALPAK": "Kara-Kalpak",
    "MACAU": "Macau",
    "SAMOA OCIDENTAL": "Western Samoa",
    "PANAMA": "Panama",
    "BELIZE": "Belize",
    "TUVIN": "Tuva",
    "GROENLANDIA": "Greenland",
    "ILHAS CHRISTMAS": "Christmas Island",
    "ILHAS WALLIS E FUTUNA": "Wallis and Futuna Islands",
    "ILHAS BAKER": "Baker Island",
    "TARTARIA": "Tartary",
    "HONG-KONG": "Hong Kong",
    "SABAH": "Sabah",
    "ILHAS PITCAIRIN": "Pitcairn Islands",
    "CHADE": "Chad",
    "TERRITORIO DE COCOS": "Cocos Islands",
    "SAN MARINO": "San Marino",
    "SAMOA AMERICANA": "American Samoa",
    "TRANSKEI": "Transkei",
    "REPUBLICA DO NIGER": "Niger",
    "UNIAO SOVIETICA": "Soviet Union",
    "REPUBLICA TCHECA": "Czech Republic",
    "CARELIA": "Karelia",
    "ILHAS MALVINAS": "Falkland Islands",
    "ILHAS GILBERT": "Gilbert Islands",
    "ILHAS COSMOLEDO (LOMORES)": "Cosmoledo Islands",
    "COMUNIDADE DOMINICANA": "Dominican Community",
    "KOMI": "Komi",
    "ILHAS MARSHALL": "Marshall Islands",
    "MOLDAVIA": "Moldova",
    "NEPAL": "Nepal",
    "TANZANIA": "Tanzania",
    "PAPUA NOVA GUINE": "Papua New Guinea",
    "KALMIR": "Kalmir",
    "RUIQUIU,IS": "Ruiqui Island",
    "GAZA": "Gaza",
    "ANTARTICO CHILENO": "Chilean Antarctica",
    "ILHAS MARIANAS": "Mariana Islands",
    "TREGUA, ESTADO": "Truce State",
    "KARACHAEVOCHERKESS": "Karachay-Cherkess",
    "ARQUIPELAGO DE BISMARK": "Bismarck Archipelago",
    "GRANDA": "Grenada",
    "ILHAS NIUE": "Niue",
    "DAOME": "Dahomey",
    "MONACO": "Monaco",
    "TANGANICA": "Tanganyika",
    "ILHAS COMORES": "Comoros",
    "RONCADOR": "Roncador",
    "ILHAS DO PACIFICO": "Pacific Islands",
    "ILHA MILHOS": "Milhos Island",
    "MALASIA": "Malaysia",
    "CINGAPURA": "Singapore",
    "ESTONIA": "Estonia",
    "MONTENEGRO": "Montenegro",
    "CHUVASH": "Chuvashia",
    "MARI": "Mari",
    "SERVIA": "Serbia",
    "ILHAS PASCOA": "Easter Island",
    "LAOS": "Laos",
    "ILHAS HOWLAND E JARVIS": "Howland and Jarvis Islands",
    "ILHAS TURKS E CAICOS": "Turks and Caicos Islands",
    "ILHAS NOVA CALEDONIA": "New Caledonia",
    "AZERBAIJAO": "Azerbaijan",
    "KMER/CAMBOJA": "Cambodia",
    "SEYCHELLES": "Seychelles",
    "MASCATE": "Muscat",
    "GUINE EQUATORIAL": "Equatorial Guinea",
    "SANTA HELENA": "Saint Helena",
    "SRI-LANKA": "Sri Lanka",
    "ILHAS CANTAO E ENDERBURG": "Canton and Enderbury Islands",
    "YAKUT": "Yakut",
    "ILHAS CANARIAS": "Canary Islands",
    "TCHECOSLOVAQUIA": "Czechoslovakia",
    "ARQUIPELAGO MIDWAY": "Midway Islands",
    "SUAZILANDIA": "Eswatini"
}
df_grouped['pais_rnaturalearth'] = df_grouped['pais'].map(recode_dict)
import requests
import zipfile
import io
url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
response = requests.get(url)
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    z.extractall("temp_shp")
world = gpd.read_file("temp_shp/ne_110m_admin_0_countries.shp")
world_data = world.merge(df_grouped, left_on='NAME', right_on='pais_rnaturalearth', how='left')
fig, ax = plt.subplots(1, 1, figsize=(15, 10))
world_data.plot(column='percentual', ax=ax, legend=True, cmap='OrRd', missing_kwds={'color': 'lightgrey'})
ax.set_title('Percentage of Emergency Hospitalizations by Country')
plt.savefig('mapa_percentual_en.png', dpi=300, bbox_inches='tight')
plt.close()
fig, ax = plt.subplots(1, 1, figsize=(15, 10))
world_data.plot(column='percentual', ax=ax, legend=True, cmap='OrRd', missing_kwds={'color': 'lightgrey'})
ax.set_title('Percentual de Internações de Urgência por País')
plt.savefig('mapa_percentual_pt.png', dpi=300, bbox_inches='tight')
plt.close()
continent_dict = {
    "Bolivia": "South America",
    "Barbados": "North America",
    "Egypt": "Africa",
    "Brunei": "Asia",
    "Zimbabwe": "Africa",
    "Botswana": "Africa",
    "Peru": "South America",
    "Ethiopia": "Africa",
    "Bahrain": "Asia",
    "Spain": "Europe",
    "Rwanda": "Africa",
    "Namibia": "Africa",
    "Chile": "South America",
    "Venezuela": "South America",
    "Bermuda": "North America",
    "Italy": "Europe",
    "Haiti": "North America",
    "Martinique": "North America",
    "Ireland": "Europe",
    "Mexico": "North America",
    "Uzbekistan": "Asia",
    "India": "Asia",
    "Germany": "Europe",
    "Portugal": "Europe",
    "Cuba": "North America",
    "Colombia": "South America",
    "Solomon Islands": "Oceania",
    "Argentina": "South America",
    "Wales": "Europe",
    "United States of America": "North America",
    "Japan": "Asia",
    "Senegal": "Africa",
    "Paraguay": "South America",
    "Ghana": "Africa",
    "Scotland": "Europe",
    "Saudi Arabia": "Asia",
    "Ukraine": "Europe",
    "Greece": "Europe",
    "Angola": "Africa",
    "Ecuador": "South America",
    "Benin": "Africa",
    "Mozambique": "Africa",
    "Tunisia": "Africa",
    "Congo": "Africa",
    "Malta": "Europe",
    "China": "Asia",
    "Gibraltar": "Europe",
    "England": "Europe",
    "Faroe Islands": "Europe",
    "Uruguay": "South America",
    "United Kingdom": "Europe",
    "United States Virgin Islands": "North America",
    "Channel Islands": "Europe",
    "Guinea-Bissau": "Africa",
    "Bahamas": "North America",
    "British Antarctic Territory": "Antarctica",
    "Sweden": "Europe",
    "British Virgin Islands": "North America",
    "Russia": "Europe",
    "Burkina Faso": "Africa",
    "Belarus": "Europe",
    "Turks and Caicos Islands": "North America",
    "Guatemala": "North America",
    "Costa Rica": "North America",
    "Canada": "North America",
    "Latvia": "Europe",
    "Montserrat": "North America",
    "Australia": "Oceania",
    "Netherlands": "Europe",
    "Cyprus": "Europe",
    "France": "Europe",
    "Australian Antarctic Territory": "Antarctica",
    "Svalbard": "Europe",
    "Iceland": "Europe",
    "Sao Tome and Principe": "Africa",
    "Serbia": "Europe",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Poland": "Europe",
    "Liberia": "Africa",
    "Hungary": "Europe",
    "South Korea": "Asia",
    "French Guiana": "South America",
    "Cameroon": "Africa",
    "Tokelau": "Oceania",
    "Andorra": "Europe",
    "Palestine": "Asia",
    "Bulgaria": "Europe",
    "Myanmar": "Asia",
    "Dominican Republic": "North America",
    "Heard Island and McDonald Islands": "Antarctica",
    "Finland": "Europe",
    "Saint Lucia": "North America",
    "Kenya": "Africa",
    "Madagascar": "Africa",
    "Bangladesh": "Asia",
    "French Afar": "Africa",
    "Nigeria": "Africa",
    "Nicaragua": "North America",
    "Panama": "North America",
    "Oman": "Asia",
    "Bosnia and Herzegovina": "Europe",
    "British Honduras": "North America",
    "Puerto Rico": "North America",
    "Taiwan": "Asia",
    "Switzerland": "Europe",
    "Gambia": "Africa",
    "Quisqueya": "North America",
    "Malawi": "Africa",
    "Belgium": "Europe",
    "Cape Verde": "Africa",
    "Jamaica": "North America",
    "Austria": "Europe",
    "Saint Kitts and Nevis": "North America",
    "Bashkortostan": "Europe",
    "Yemen": "Asia",
    "Kyrgyzstan": "Asia",
    "Lesotho": "Africa",
    "Sri Lanka": "Asia",
    "Indonesia": "Asia",
    "Gorno-Altai": "Asia",
    "Mauritius": "Africa",
    "Spanish Sahara": "Africa",
    "Antigua and Barbuda": "North America",
    "Northern Ireland": "Europe",
    "Mauritania": "Africa",
    "British Indian Ocean Territory": "Asia",
    "Curacao": "North America",
    "Turkey": "Asia",
    "Line Islands": "Oceania",
    "Madeira": "Europe",
    "Suriname": "South America",
    "Ceuta and Melilla": "Europe",
    "Jordan": "Asia",
    "Vatican": "Europe",
    "Tajikistan": "Asia",
    "New Hebrides": "Oceania",
    "Kingman Reef": "Oceania",
    "Guam": "Oceania",
    "Morocco": "Africa",
    "Aruba": "North America",
    "Netherlands Antilles": "North America",
    "Wake Island": "Oceania",
    "South Africa": "Africa",
    "Liechtenstein": "Europe",
    "Israel": "Asia",
    "Argentine Antarctica": "Antarctica",
    "Sarawak": "Asia",
    "Denmark": "Europe",
    "Guyana": "South America",
    "Guinea": "Africa",
    "Qatar": "Asia",
    "Georgia": "Asia",
    "Somalia": "Africa",
    "Guadeloupe": "North America",
    "Ivory Coast": "Africa",
    "El Salvador": "North America",
    "Cook Islands": "Oceania",
    "Kabardino-Balkaria": "Europe",
    "Romania": "Europe",
    "Norway": "Europe",
    "Thailand": "Asia",
    "Central African Republic": "Africa",
    "Lithuania": "Europe",
    "Balearic Islands": "Europe",
    "Luxembourg": "Europe",
    "Philippines": "Asia",
    "Saint Pierre and Miquelon": "North America",
    "Iraq": "Asia",
    "Azores": "Europe",
    "New Guinea": "Oceania",
    "Buryatia": "Asia",
    "Palau": "Oceania",
    "Croatia": "Europe",
    "Libya": "Africa",
    "Timor-Leste": "Asia",
    "Armenia": "Asia",
    "Syria": "Asia",
    "Gabon": "Africa",
    "Togo": "Africa",
    "Pakistan": "Asia",
    "Mali": "Africa",
    "Lebanon": "Asia",
    "Ashmore and Cartier Islands": "Oceania",
    "United Arab Emirates": "Asia",
    "Kuwait": "Asia",
    "Saint Vincent and the Grenadines": "North America",
    "Manahiki": "Oceania",
    "Mongolia": "Asia",
    "Congo - Kinshasa": "Africa",
    "Slovenia": "Europe",
    "Afghanistan": "Asia",
    "North Vietnam": "Asia",
    "Uganda": "Africa",
    "Iran": "Asia",
    "Ascension and Tristan da Cunha": "Africa",
    "Slovakia": "Europe",
    "Honduras": "North America",
    "Kazakhstan": "Asia",
    "Zambia": "Africa",
    "Sudan": "Africa",
    "Northern African Territories": "Africa",
    "Sierra Leone": "Africa",
    "Serran Islands": "Oceania",
    "Dagestan": "Europe",
    "Maldives": "Asia",
    "Tuvalu": "Oceania",
    "New Zealand": "Oceania",
    "Eswatini": "Africa",
    "South-West African Protectorate": "Africa",
    "Trinidad and Tobago": "North America",
    "Johnston Island": "Oceania",
    "Ifni": "Africa",
    "Djibouti": "Africa",
    "North Macedonia": "Europe",
    "Tonga": "Oceania",
    "Norwegian Antarctica": "Antarctica",
    "French Polynesia": "Oceania",
    "Bhutan": "Asia",
    "South Yemen": "Asia",
    "Burundi": "Africa",
    "French Antarctic Territory": "Antarctica",
    "Falkland Islands": "South America",
    "South Vietnam": "Asia",
    "Kalimantan": "Asia",
    "Kara-Kalpak": "Asia",
    "Macau": "Asia",
    "Western Samoa": "Oceania",
    "Belize": "North America",
    "Tuva": "Asia",
    "Greenland": "North America",
    "Christmas Island": "Oceania",
    "Wallis and Futuna Islands": "Oceania",
    "Baker Island": "Oceania",
    "Tartary": "Asia",
    "Hong Kong": "Asia",
    "Sabah": "Asia",
    "Pitcairn Islands": "Oceania",
    "Chad": "Africa",
    "Cocos Islands": "Oceania",
    "San Marino": "Europe",
    "American Samoa": "Oceania",
    "Transkei": "Africa",
    "Niger": "Africa",
    "Soviet Union": "Europe",
    "Czech Republic": "Europe",
    "Karelia": "Europe",
    "Gilbert Islands": "Oceania",
    "Cosmoledo Islands": "Africa",
    "Dominican Community": "North America",
    "Komi": "Europe",
    "Marshall Islands": "Oceania",
    "Moldova": "Europe",
    "Nepal": "Asia",
    "Tanzania": "Africa",
    "Papua New Guinea": "Oceania",
    "Kalmir": "Asia",
    "Ruiqui Island": "Oceania",
    "Gaza": "Asia",
    "Chilean Antarctica": "Antarctica",
    "Mariana Islands": "Oceania",
    "Truce State": "Asia",
    "Karachay-Cherkess": "Europe",
    "Bismarck Archipelago": "Oceania",
    "Grenada": "North America",
    "Niue": "Oceania",
    "Dahomey": "Africa",
    "Monaco": "Europe",
    "Tanganyika": "Africa",
    "Comoros": "Africa",
    "Roncador": "North America",
    "Pacific Islands": "Oceania",
    "Milhos Island": "Africa",
    "Malaysia": "Asia",
    "Singapore": "Asia",
    "Estonia": "Europe",
    "Montenegro": "Europe",
    "Chuvashia": "Europe",
    "Mari": "Europe",
    "Laos": "Asia",
    "Easter Island": "Oceania",
    "Howland and Jarvis Islands": "Oceania",
    "New Caledonia": "Oceania",
    "Azerbaijan": "Asia",
    "Cambodia": "Asia",
    "Seychelles": "Africa",
    "Muscat": "Asia",
    "Equatorial Guinea": "Africa",
    "Saint Helena": "Africa",
    "Canton and Enderbury Islands": "Oceania",
    "Yakut": "Asia",
    "Canary Islands": "Europe",
    "Czechoslovakia": "Europe",
    "Midway Islands": "Oceania",
}
df['continentes'] = df['pais'].map(recode_dict).map(continent_dict)
estrangeiros_por_continente_ano = df.groupby(['ANO_CMPT', 'continentes']).size().reset_index(name='qtd')
df_pivot = estrangeiros_por_continente_ano.pivot(index='ANO_CMPT', columns='continentes', values='qtd').fillna(0)
df_pivot_en = df_pivot.copy()
df_pivot_en = df_pivot_en[df_pivot_en.sum().sort_values().index]
ax = df_pivot_en.plot.area(figsize=(10, 6), stacked=True)
def mil_formatter_en(x, pos):
    if x >= 1000:
        return f"{int(x/1000)}k"
    else:
        return str(int(x))
plt.gca().yaxis.set_major_formatter(FuncFormatter(mil_formatter_en))
plt.title("Annual emergency hospital admissions of foreign nationals in Brazil's Unified Health System (SUS) by continent")
plt.xlabel("Year")
plt.ylabel("Number of hospitalizations")
plt.legend(title='Continents', bbox_to_anchor=(1.05, 1), loc='upper left')
max_y = df_pivot_en.sum(axis=1).max()
for i, row in df_pivot_en.iterrows():
    valor = row.sum()
    label = mil_formatter_en(valor, None)
    plt.text(i, valor + max_y * 0.02, label, ha="center", va="bottom", fontsize=10)
plt.figtext(0.5, -0.01, "Source: SIH/SUS – Sistema de Informações Hospitalares do SUS (Datasus).", ha="center", fontsize=9, style="italic")
plt.figtext(0.5, -0.05, "Note: 2025 data is partial (up to August 2025)", ha="center", fontsize=9, style="italic")
plt.subplots_adjust(bottom=0.2)
plt.tight_layout()
plt.savefig('grafico_area_en.png', dpi=300, bbox_inches='tight')
plt.close()
continent_translation = {
    'Africa': 'África',
    'Asia': 'Ásia',
    'Europe': 'Europa',
    'North America': 'América do Norte',
    'South America': 'América do Sul',
    'Oceania': 'Oceania',
    'Antarctica': 'Antártica'
}
df_pivot_pt = df_pivot.rename(columns=continent_translation)
df_pivot_pt = df_pivot_pt[df_pivot_pt.sum().sort_values().index]
ax = df_pivot_pt.plot.area(figsize=(10, 6), stacked=True)
def mil_formatter_pt(x, pos):
    if x >= 1000:
        return f"{int(x/1000)} mil"
    else:
        return str(int(x))
plt.gca().yaxis.set_major_formatter(FuncFormatter(mil_formatter_pt))
plt.title("Internações com urgência de pessoas estrangeiras no SUS por continente")
plt.xlabel("Ano")
plt.ylabel("Quantidade de internações")
plt.legend(title='Continentes', bbox_to_anchor=(1.05, 1), loc='upper left')
max_y = df_pivot_pt.sum(axis=1).max()
for i, row in df_pivot_pt.iterrows():
    valor = row.sum()
    label = mil_formatter_pt(valor, None)
    plt.text(i, valor + max_y * 0.02, label, ha="center", va="bottom", fontsize=10)
plt.figtext(0.5, -0.01, "Fonte: SIH/SUS – Sistema de Informações Hospitalares do SUS (Datasus).", ha="center", fontsize=9, style="italic")
plt.figtext(0.5, -0.05, "Nota: Dados de 2025 são parciais (até agosto de 2025)", ha="center", fontsize=9, style="italic")
plt.subplots_adjust(bottom=0.2)
plt.tight_layout()
plt.savefig('grafico_area_pt.png', dpi=300, bbox_inches='tight')
plt.close()